FROM node:20 AS base

# CONFIGURE PNPM STUFF
ENV PNPM_HOME="/pnpm"

ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

# SETUP WORKDIR AND BUILD

WORKDIR /app

COPY backend ./backend
COPY dtos ./dtos
COPY pnpm-workspace.yaml .
COPY pnpm-lock.yaml .

RUN pnpm install

# RUN in dev mode
CMD [ "pnpm", "--filter", "todo-backend", "run", "start" ]